---
version: '3.8'
services:
  database:
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
    image: mysql:${MYSQL_VERSION:-5.7}

  phpunit:
    command:
      - bash
    depends_on:
      - database
    environment:
      DATABASE_PASSWORD: examplepass
      WORDPRESS_VERSION: ${WORDPRESS_VERSION:-latest}
    image: ${DOCKER_IMAGE_PHPUNIT:-futureys/phpunit-wordpress-plugin}
    stdin_open: true
    tty: true
    volumes:
      - ${PATH_TO_INDIVIDUAL_PLUGIN_DIRECTORY:?err}:/plugin
