---
version: '3.7'
services:
  database:
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
    image: mysql:${MYSQL_VERSION:-5.7}

  phpunit:
    command:
      - bash
    container_name: phpunit
    depends_on:
      - database
    environment:
      DATABASE_PASSWORD: examplepass
    image: ${DOCKER_IMAGE_PHPUNIT:-futureys/phpunit-wordpress-plugin}
    stdin_open: true
    tty: true
    volumes:
      - ${PATH_TO_INDIVIDUAL_PLUGIN_DIRECTORY:?err}:/plugin
