#!/usr/bin/env bash
set -eu

DATABASE_NAME=${DATABASE_NAME-wordpress}
DATABASE_USER=${DATABASE_USER-root}
DATABASE_PASSWORD=${DATABASE_PASSWORD}
DATABASE_HOST=${DATABASE_HOST-database}

wait-for-it "${DATABASE_HOST}" -- install-wp-tests "${DATABASE_NAME}" "${DATABASE_USER}" "${DATABASE_PASSWORD}" "${DATABASE_HOST}" 4.3
exec "${@}"
